apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-elasticsearch-output
  namespace: logging
data:
  fluentd.conf: |
    # Ignore fluentd own events
    <match fluent.**>
      @type null
    </match>

    # TCP input to receive logs from the forwarders
    <source>
      @type forward
      bind 0.0.0.0
      port 24224
    </source>

    # HTTP input for the liveness and readiness probes
    <source>
      @type http
      bind 0.0.0.0
      port 9880
    </source>

    # Throw the healthcheck to the standard output instead of forwarding it
    <match fluentd.healthcheck>
      @type stdout
    </match>

    # rewrite tags based on which namespace the logs come from.
    <match kube.**>
      @type rewrite_tag_filter
      <rule>
        key     $['kubernetes']['namespace_name']
        pattern /^(kube-system|kubeapps|k8s-system-[\S]+)$/
        tag     ops.${tag}
      </rule>
      <rule>
        key     $['kubernetes']['namespace_name']
        pattern /.+/
        tag     prod.${tag}
      </rule>
    </match>
    

    <match **>
      @type elasticsearch
      @id output_elasticsearch
      host elasticsearch-client.logging.svc.cluster.local
      port 9200
      logstash_format true
      logstash_prefix kube.${record['kubernetes']['namespace_name']}
      <buffer>
        @type file
        path /opt/bitnami/fluentd/logs/buffers/logs.buffer
        flush_thread_count 2
        flush_interval 5s
      </buffer>
    </match>
